spring:
  profiles:
    active: dev

name: NAMEINFILE

a: A

animal:
  dog: wang
  fish:
    fat_head_fish: rua
  cat: miao

game:
  - diablo
  - worldOfWarcraft
  - startcraft

---
spring:
  profiles: dev
  redis:
    host: 47.105.97.246
    port: 6379
    password: sunjian
    pool:
      max-wait: -1
    database: 0

pf: DEV

---
spring:
  profiles: prod

pf: PROD